name: Validate link references in built HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  check_link_references:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          submodules: "recursive"
      - name: Build
        run: make build
        env:
          DISABLE_TESTS: 1
      - uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6
        with:
          python-version: "3.x"
      - run: python tool/check_link_references.py
